services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TRANSMISSION_TZ}
      - TRANSMISSION_WEB_HOME=
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      - WHITELIST=
      - PEERPORT=
      - HOST_WHITELIST=
    volumes:
      - data:/config
      - downloads:/downloads #optional
      - watch:/watch #optional
    ports:
      - '127.0.0.1:4043:9091'
      - 51413:51413
      - 51413:51413/udp
    networks:
      - main
    restart: unless-stopped

networks:
  main:
    driver: bridge

volumes:
  data:
  downloads:
  watch:
